#!/bin/bash
PROFILE=bac-mau-business
BUCKET=s3://huy-business.com
DISTRIBUTION_ID=E2SRECAIZ04S2Y

# Remove all existing files in the bucket
echo "Deleting all existing files in the bucket"
aws s3 --profile $PROFILE rm "$BUCKET" --recursive

# Upload from dist folder
echo "Uploading files in the dist folder"
aws s3 --profile $PROFILE cp dist/bac-mau-business-web "$BUCKET" --recursive

# Invalidate cache from CloudFront

aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"