#!/bin/bash
PROFILE=bac-mau-business
# BUCKET=s3://venusspa.net
# BUCKET=s3://life-reflexology.com
BUCKET=s3://tictex.io
# DISTRIBUTION_ID=E360ORER2635Z7 # venusspa.net
# DISTRIBUTION_ID=E129VLBXO9IILY # life-reflexology.com
DISTRIBUTION_ID=E11PZY8Q4GECJV # tictex.io

# # Remove all existing files in the bucket
echo "Deleting all existing files in the bucket"
aws s3 --profile $PROFILE rm "$BUCKET" --recursive

# # Upload from dist folder
echo "Uploading files in the dist folder"
aws s3 --profile $PROFILE cp dist/bac-mau-business-web "$BUCKET" --recursive

# Invalidate cache from CloudFront
aws cloudfront create-invalidation \
    --profile=$PROFILE \
    --output=text \
    --distribution-id "$DISTRIBUTION_ID" \
    --paths "/*" | cat